name: Update Badges

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Badges
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID
          filename: test-status.json
          label: tests
          message: ${{ github.event.workflow_run.conclusion }}
          color: ${{ github.event.workflow_run.conclusion == 'success' && 'success' || 'critical' }}