name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install chromium --with-deps
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0

    - name: Run Playwright tests
      run: npm run test
      env:
        CI: true
        # Ensure headless mode
        PLAYWRIGHT_HEADLESS: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

    # Optional: Publish Test Report in GitHub Actions
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: 'test-results/junit.xml'

    # Optional: Add test summary
    - name: Add Test Summary
      if: always()
      run: |
        echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✨ Tests completed at $(date)" >> $GITHUB_STEP_SUMMARY
        if [ -f "test-results/report.json" ]; then
          echo "### Summary" >> $GITHUB_STEP_SUMMARY
          cat test-results/report.json | jq -r '"- Total: \(.total)\n- Passed: \(.passed)\n- Failed: \(.failed)\n- Skipped: \(.skipped)"' >> $GITHUB_STEP_SUMMARY
        fi

